//======================================================================
//
// tb_chacha_qr.v
// ----------------
// Testbench for the ChaCha stream cipher qr module. This TB verifies
// that the chacha20 core can be used as specified in RFC 7539.
// Testvectors are taken from the RFC.
//
//
// Copyright (c) 2016, Assured AB
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or
// without modification, are permitted provided that the following
// conditions are met:
//
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in
//    the documentation and/or other materials provided with the
//    distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
// FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
// COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//======================================================================

module tb_chacha20_qr();


  //----------------------------------------------------------------
  // Register and Wire declarations.
  //----------------------------------------------------------------
  reg [31 : 0] tb_a;
  reg [31 : 0] tb_b;
  reg [31 : 0] tb_c;
  reg [31 : 0] tb_d;

  wire [31 : 0] tb_a_prim;
  wire [31 : 0] tb_b_prim;
  wire [31 : 0] tb_c_prim;
  wire [31 : 0] tb_d_prim;


  //----------------------------------------------------------------
  // chacha_core device under test.
  //----------------------------------------------------------------

  chacha_qr dut(
                .a(tb_a),
                .b(tb_b),
                .c(tb_c),
                .d(tb_d),
                .a_prim(tb_a_prim),
                .b_prim(tb_b_prim),
                .c_prim(tb_c_prim),
                .d_prim(tb_d_prim)
               );


  //----------------------------------------------------------------
  // chacha_qr_test
  //----------------------------------------------------------------
  initial
    begin : chacha20_qr_test
      $display("   -- Testbench for chacha20 qr module started --");
      $display("");

      // Testvectors from RFC 7539, chapter 2.1.1.
      $display("*** Applying test vector to qr module.");
      tb_a = 32'h11111111;
      tb_b = 32'h01020304;
      tb_c = 32'h9b8d6f43;
      tb_d = 32'h01234567;
      #1;

      $display("a      = 0x%08x, b      = 0x%08x, c      = 0x%08x, d      = 0x%08x",
               tb_a, tb_b, tb_c, tb_d);
      $display("a_prim = 0x%08x, b_prim = 0x%08x, c_prim = 0x%08x, d_prim = 0x%08x",
               tb_a_prim, tb_b_prim, tb_c_prim, tb_d_prim);
      $display("");

      if ((tb_a_prim != 32'hea2a92f4) || (tb_b_prim != 32'hcb1cf8ce) ||
          (tb_c_prim != 32'h4581472e) || (tb_d_prim != 32'h5881c4bb))
        $display("*** Error: Incorrect result generated by the qr module.");
      else
        $display("*** Correct result generated by the qr module.");
      $display("");

      $display("   -- Testbench for chacha20 qr module done --");
      $finish;
    end // chacha20_qr_test

endmodule // tb_chacha20_qr

//======================================================================
// EOF tb_chacha20_qr.v
//======================================================================
